### ISSUE TITLE
Exporter is broken after `dataclasses-json` Update

### ISSUE THREAD

**Issue by cr-assafbendavid** [observeinc/observe-export#15]
Recently, the package `dataclasses-json` was updated. Since then, the exporter has been broken.
Deserialization of the config file fails with the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/observe_export/observe_export.py", line 981, in export
    ec = load_export_config_from_file(Path(config_file))
  File "/usr/local/lib/python3.10/site-packages/observe_export/observe_export.py", line 722, in load_export_config_from_file
    if "dataset" in export_config.datasource:
TypeError: argument of type 'DataSourceDataset' is not iterable
```
I believe the new version of `dataclasses-json` treats `Union` types differently...

A quick fix would be to simply pin the version of the `dataclasses-json` requirement to an older version.

**Comment by MatthiasObserve** [comment]
Thanks a lot for raising this @cr-assafbendavid !
